name: Run Java Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Tests
        run: mvn test

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: reports/report.html

      - name: Send Extent Report Mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          subject: Automation Test Extent Report

          to: subbiahkarthick2004@gmail.com
          from: Github Actions

          html_body: |
            <h2>Automation Test Execution Completed</h2>
            <p>Please find the attached Extent Report.</p>

          attachments: reports/report.html